# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
global:
  rabbitmq:
    host:
    #This is hardcoding it to this machine, but there may be a better way by pointing to the deployment
      value: "full-zebra-rabbitmq"
    username:
      value: guest
    password:
      value: guest
  keycloak:
    #This is hardcoding it to this machine, but there may be a better way by pointing to the deployment
    url: "http://activiti-keycloak.192.168.1.105.nip.io/auth"
    name: keycloak
    service:
      type: http
      port: 80
db:
  uri: ""
  name: activitipostgresql
  deployPostgres: false
  port: 5432

activitipostgresql:
   postgresPassword: activiti

javaOpts:
  xmx: 768m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
image:
  repository: activiti-cloud-runtime-bundle-hello-world-image
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: activiti-cloud-runtime-bundle-hello-world
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    memory: 768Mi
  requests:
    cpu: 400m
    memory: 768Mi
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 140
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 4
readinessProbe:
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
terminationGracePeriodSeconds: 20

ingress:
  ## Set to true to enable ingress record generation
  enabled: false
